<a href="https://colab.research.google.com/github/Pranav2092/Pytorch-Practice/blob/main/Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

In [4]:
my_list = [1,2,3,4,5,6]
my_list

[1, 2, 3, 4, 5, 6]

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.38403727, 0.14438218, 0.368927  , 0.0453427 ],
       [0.07483243, 0.55118207, 0.54736278, 0.35801143],
       [0.91716934, 0.1421454 , 0.92940472, 0.8226306 ]])

In [6]:
np1.dtype

dtype('float64')

In [7]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.5988,  0.2331,  0.3130, -0.5193],
        [ 2.1681, -1.9822,  0.7757, -0.7349],
        [-0.9986, -0.3630,  0.4693, -1.1447]])

In [8]:
tensor_2d.dtype

torch.float32

In [10]:
# Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.3840, 0.1444, 0.3689, 0.0453],
        [0.0748, 0.5512, 0.5474, 0.3580],
        [0.9172, 0.1421, 0.9294, 0.8226]], dtype=torch.float64)