<a href="https://colab.research.google.com/github/Pranav2092/Pytorch-Practice/blob/main/Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import torch
import numpy as np

In [46]:
my_list = [1,2,3,4,5,6]
my_list

[1, 2, 3, 4, 5, 6]

In [47]:
np1 = np.random.rand(3,4)
np1

array([[0.46750249, 0.33552225, 0.16182929, 0.63215865],
       [0.98704519, 0.62264337, 0.31219602, 0.64584   ],
       [0.66795976, 0.57378087, 0.33359761, 0.97639215]])

In [48]:
np1.dtype

dtype('float64')

In [49]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.7658, -0.2191, -1.9850, -1.0678],
        [ 0.2418,  0.9116, -1.1493, -0.1949],
        [ 0.8696,  0.0829,  0.0852,  0.3013]])

In [50]:
tensor_2d.dtype

torch.float32

In [51]:
# Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4675, 0.3355, 0.1618, 0.6322],
        [0.9870, 0.6226, 0.3122, 0.6458],
        [0.6680, 0.5738, 0.3336, 0.9764]], dtype=torch.float64)

In [52]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
# reshape and view
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [54]:
# reshape if we dont know the no. of items using -1
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [55]:
my_torch2 = my_torch2.reshape(-1,3)
my_torch2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [56]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
my_torch3 = my_torch3.view(-1,2)
my_torch3

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [58]:
# with reshape and view, they will update
my_torch4 = torch.arange(10)
my_torch4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
my_torch5 = my_torch4.reshape(2,5)
my_torch5

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [60]:
my_torch4[1] = 4141
my_torch4

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [61]:
my_torch5

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [62]:
#slices
my_torch6 = torch.arange(10)
my_torch6

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
# Grab a specific item
my_torch6[7]

tensor(7)

In [64]:
my_torch7 = my_torch6.reshape(5,2)
my_torch7

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [65]:
my_torch7[:,1]

tensor([1, 3, 5, 7, 9])

In [66]:
# return column
my_torch7[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [67]:
#Basic tensor math operations

In [68]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [69]:
#Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [70]:
# Addition long hand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [71]:
# Subtraction
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [72]:
# sub fxn
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [73]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [74]:
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [75]:
# Divivision
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [76]:
# Division long hand
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [77]:
#remainders
tensor_b%tensor_a

tensor([0, 0, 1, 0])

In [78]:
# remainder long hand
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [79]:
#Exponent /  power
torch.pow(tensor_b,tensor_a)

tensor([   5,   36,  343, 4096])

In [80]:
tensor_b ** tensor_a

tensor([   5,   36,  343, 4096])

In [81]:
#Another way to write long hand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [82]:
#Reassignment
#tensor_a += tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [83]:
tensor_a

tensor([ 6,  8, 10, 12])